// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char THING_ID[]           = "b99ec34d-1e91-475e-89c8-42b6e9185e0e";
const char DEVICE_LOGIN_NAME[]  = "11ba65d1-8670-46e4-b273-95c89358acbc";

const char SSID[]               = "IOT LAB";                   // Network SSID (name)
const char PASS[]               = "iotlab@2022";                // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]         = "TB20QH6GFFTIVMGAW7G8";     // Secret device password

void onREALY1Change();
void onREALY2Change();
void onRELAY3Change();

bool rEALY_1;
bool rEALY_2;
bool rELAY_3;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(rEALY_1, READWRITE, ON_CHANGE, onREALY1Change);
  ArduinoCloud.addProperty(rEALY_2, READWRITE, ON_CHANGE, onREALY2Change);
  ArduinoCloud.addProperty(rELAY_3, READWRITE, ON_CHANGE, onRELAY3Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
